In [227]:
import pandas

In [228]:
titled_players_df = pandas.read_csv("./titled-players.csv")

In [229]:
titled_players_df.shape[0]

1904

In [230]:
titled_players_df['title'].value_counts()

title
GM    1572
IM     332
Name: count, dtype: int64

In [231]:
gm_players_df = titled_players_df[titled_players_df["title"] == "GM"]
im_players_df = titled_players_df[titled_players_df["title"] == "IM"]
fm_players_df = titled_players_df[titled_players_df["title"] == "FM"]
cm_players_df = titled_players_df[titled_players_df["title"] == "CM"]
nm_players_df = titled_players_df[titled_players_df["title"] == "NM"]
wgm_players_df = titled_players_df[titled_players_df["title"] == "WGM"]
wim_players_df = titled_players_df[titled_players_df["title"] == "WIM"]
wfm_players_df = titled_players_df[titled_players_df["title"] == "WFM"]
wcm_players_df = titled_players_df[titled_players_df["title"] == "WCM"]
wnm_players_df = titled_players_df[titled_players_df["title"] == "WNM"]

## Rapid

In [232]:
titled_players_df["rapid_rating_last"].mean()

1669.4290966386554

In [233]:
column: str = "rapid_rating_best"
max_rapid: int = titled_players_df[column].max()
max_rapid_player = titled_players_df[titled_players_df[column] == max_rapid]
max_rapid_player[["id", "username", "name", column]]

           id        username             name  rapid_rating_best
441  11177810  fabianocaruana  Fabiano Caruana               3045

## Blitz

In [234]:
titled_players_df["blitz_rating_last"].mean()

2547.890756302521

In [235]:
column : str = "blitz_rating_best"
max_blitz : int = titled_players_df[column].max()
max_blitz_player = titled_players_df[titled_players_df[column] == max_blitz]
max_blitz_player[["id", "username", "name", column]]

           id username             name  blitz_rating_best
687  15448422   hikaru  Hikaru Nakamura               3405

## Bullet

In [236]:
titled_players_df["bullet_rating_last"].mean()

2132.9553571428573

In [237]:
column: str = "bullet_rating_best"
max_bullet: int = titled_players_df[column].max()
max_bullet_player = titled_players_df[titled_players_df[column] == max_bullet]
max_bullet_player[["id", "username", "name", column]]

           id username             name  bullet_rating_best
687  15448422   hikaru  Hikaru Nakamura                3570